# .travis.yml
addons:
  postgresql: "9.4"
  apt:
    packages:
      - postgresql-contrib-9.4
      - postgresql-9.4-plv8

notifications:
  slack: healthsamurai:711fu4qu2Pz0uWrc8JMQ6Bz7

script: sudo su $USER -c "env PGUSER=postgres DB=test ./runme integrate"
after_success: ./build/release.sh
